version: "3"

services:
  node:
    image: immortalvlad/test
    build: .
    ports:
      - "1234:80"
    #user: "node"
    #working_dir: /home/node/app
    #environment:
    #  - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    #expose:
      #- "801"